name: 'otvetoved-backend'
services:
  api-dev:
    build: ./app
    image: 127.0.0.1:5000/otbetoved-backend-app
    env_file:
      - app/.env.sample
      - app/.env
    ports:
      - ${COMPOSE_APP_DEV_EXPOSE_HOST}:${COMPOSE_APP_DEV_EXPOSE_PORT}:8000
    profiles:
      - dev
    depends_on:
      - postgres
  api-prod:
    build:
      context: ./app
      dockerfile: ./app/Dockerfile.prod
    image: 127.0.0.1:5000/otbetoved-backend-app
    env_file:
      - app/.env.sample
      - app/.env
    profiles:
      - prod
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    image: 127.0.0.1:5000/otbetoved-backend-nginx
    env_file:
      - nginx/.env.sample
      - config/.env
    profiles:
      - prod
  postgres:
    image: postgres:16
    env_file:
      - postgres/.env.sample
      - postgres/.env
    ports:
      - ${COMPOSE_POSTGRES_EXPOSE_HOST}:${COMPOSE_POSTGRES_EXPOSE_PORT}:5432
