name: 'otvetoved-application-prod'

services:
  backend:
    profiles:
      - prod
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile.prod
    image: ${COMPOSE_REGISTRY_URI}/otbetoved-backend-prod
    env_file:
      - backend/.env.sample
      - backend/.env
    depends_on:
      - postgres
  frontend:
    profiles:
      - dev
      - prod
    build:
      context: ./frontend
    image: ${COMPOSE_REGISTRY_URI}/otvetoved-frontend-prod
    env_file:
      - frontend/.env.sample
      - frontend/.env
    depends_on:
      - backend-dev
    volumes:
      - ./frontend:/app
    command: npm run docker-dev
  nginx:
    build: ./nginx
    env_file:
      - nginx/.env.sample
      - nginx/.env
    ports:
      - ${COMPOSE_NGINX_HTTP_HOST}:${COMPOSE_NGINX_HTTP_PORT}:8000
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:16
    env_file:
      - postgres/.env.sample
      - postgres/.env
    ports:
      - ${COMPOSE_POSTGRES_EXPOSE_HOST}:${COMPOSE_POSTGRES_EXPOSE_PORT}:5432
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
