name: 'otvetoved-application-dev'

services:
  backend:
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - ${COMPOSE_BACKEND_DEV_EXPOSE_HOST}:${COMPOSE_BACKEND_DEV_EXPOSE_PORT}:8000
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/usr/src/app/src
  frontend:
    build:
      context: ./frontend
    env_file:
      - frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run docker-dev
  nginx:
    build: ./nginx
    env_file:
      - nginx/.env
    ports:
      - ${COMPOSE_NGINX_HTTP_HOST}:${COMPOSE_NGINX_HTTP_PORT}:8000
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx:/nginx
  postgres:
    image: postgres:16
    env_file:
      - postgres/.env
    ports:
      - ${COMPOSE_POSTGRES_EXPOSE_HOST}:${COMPOSE_POSTGRES_EXPOSE_PORT}:5432
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 10
  run-migrations:
    build: ./backend
    depends_on:
      - postgres
    command: alembic upgrade head
    env_file:
      - backend/.env
volumes:
  database:
