"""Add answer fields and created_at fields

Revision ID: 2ba4c48ff4c8
Revises: 645c1558197a
Create Date: 2024-06-29 01:31:40.898666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba4c48ff4c8'
down_revision: Union[str, None] = '645c1558197a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('question', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('question_answer', sa.Column('created_by_user_id', sa.Integer(), nullable=False))
    op.add_column('question_answer', sa.Column('text', sa.String(), nullable=False))
    op.add_column('question_answer', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'question_answer', 'user', ['created_by_user_id'], ['id'])
    op.add_column('question_tag', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tag', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_session', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'user_session', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='foreignkey')
    op.drop_column('user_session', 'created_at')
    op.drop_column('user', 'created_at')
    op.drop_column('tag', 'created_at')
    op.drop_column('question_tag', 'created_at')
    op.drop_constraint(None, 'question_answer', type_='foreignkey')
    op.drop_column('question_answer', 'created_at')
    op.drop_column('question_answer', 'text')
    op.drop_column('question_answer', 'created_by_user_id')
    op.alter_column('question', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('question', 'created_at')
    # ### end Alembic commands ###
