name: Running Tests

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools
          cd backend
          pip-compile --extra dev
          pip install -r requirements.txt
          pip install .

      - name: Lint with ruff
        run: |
          ruff check ./backend/src

      - name: Sync, rebuild and restart production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: cd otvetoved && git pull && docker compose up --build -d
